### ISSUE TITLE
feat(git): Create Git Repository

### ISSUE THREAD

**Issue by refcell** [refcell/amble#55]
**Description**

Adds a `--git` flag to amble that allows amble to automatically create a github repo under the user's username.

The `--git` flag should be of type `Option<Option<String>>` where the inner string is the user's github username. If it is not specified, amble should try to grab the username like done for the cargo toml `repository url` field.

When the `--full` flag is provided, git repo generation should be enabled by default.

**Comment by quangkeu95** [comment]
As I understand that if the `--git` flag is set, then we init the git repository first, then we set the remote tracked repository to the url that includes the github user's username, is it right?

**Comment by quangkeu95** [comment]
Still not knowing how to grab the username if user input is not provided, please enlighten me !! Also, for the user remote origin url, should I use this format by default: `git@github.com:username/new_repo` ?
